# file that allows project setup settings


spring.application.name=Board_System_Spring_Project

# connect spring boot with local mysql
# class name that connects mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# address to connect
spring.datasource.url=jdbc:mysql://localhost:3306/{your_DB_name}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username={your_DB_username}
spring.datasource.password={your_DB_password}

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# swagger setting
# swagger API path
springdoc.api-docs.path=/v3/api-docs
# swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html
# API sort method in swagger UI (sort in method)
springdoc.swagger-ui.operations-sorter=method
